export const experienceData = [
  {
    id: 'infocentro-instrutor',
    company: 'Infocentro',
    current: true,
    titlePt: 'Instrutor Curso de Informática',
    titleEn: 'IT Course Instructor',
    datePt: 'Abr 2025 – Atual · CLT',
    dateEn: 'Apr 2025 – Present · CLT',
    descPt: 'Instrutor de informática básica, incluindo uso do sistema operacional Linux e pacote LibreOffice.',
    descEn: 'Basic IT instructor, including Linux OS and LibreOffice suite.',
    tags: ['Linux', 'Writer', 'Calc', 'Impress'],
  },
  {
    id: 'freelancer-fivem-dev',
    company: 'Freelancer',
    titlePt: 'Desenvolvedor em servidor de Jogos Online',
    titleEn: 'Online Game Server Developer',
    datePt: '2025 - Estágio',
    dateEn: '2025 - Internship',
    descPt: 'Trabalho como desenvolvedor freelancer para servidores FiveM.',
    descEn: 'Working as a freelance developer for FiveM servers.',
    tags: ['Python', 'JavaScript', 'Lua', 'SQL', 'MySQL', 'HeidiSQL'],
  },
  {
    id: 'freelancer-fivem-modeler',
    company: 'Freelancer',
    titlePt: 'Modelador de Mods FIVEM',
    titleEn: 'FIVEM Mod Modeler',
    datePt: 'Dez 2019 – 2020',
    dateEn: 'Dec 2019 – 2020',
    descPt: 'Modelagem de interface de itens para o jogo FiveM.',
    descEn: 'Item interface modeling for the FiveM game.',
    tags: ['Photoshop', 'OpenIV', 'Codewalker'],
  },
  {
    id: 'computec-instrutor',
    company: 'Computec',
    titlePt: 'Instrutor Curso de Informática',
    titleEn: 'IT Course Instructor',
    datePt: 'Início 2023 ao fim de 2023',
    dateEn: 'Early 2023 to late 2023',
    descPt: 'Instrutor de informática básica com foco no pacote Microsoft Office.',
    descEn: 'Basic IT instructor focused on Microsoft Office suite.',
    tags: ['Windows 10', 'Word', 'Excel', 'PowerPoint'],
  },
];
